In [1]:
with open("input4.txt") as f:
    data = f.read().splitlines()

nums = [int(x) for x in data[0].split(",")]
data = data[1:]

In [2]:
boards = []

for i in range(0, len(data), 6):
    board = data[i+1:i+6]
    board = [
        [int(x) for x in row.split()]
        for row in board
    ]
    boards.append(board)

In [34]:
import numpy as np

marked = np.zeros(
    (
        len(boards), 
        len(boards[0]), 
        len(boards[0][0])
    ), dtype=bool)

boards = np.array(boards)
done = False


win = marked.all(axis=1).any(axis=1) | marked.all(axis=2).any(axis=1)
for step, x in enumerate(nums):
    marked = (boards == x) | marked
    new_win = marked.all(axis=1).any(axis=1) | marked.all(axis=2).any(axis=1)
    
    if new_win.all():
        break
    win = new_win
    

In [39]:
(~marked[21] * boards[21]).sum() * x

5434

In [37]:
(~win).nonzero()

(array([21], dtype=int64),)

In [27]:
marked.all(axis=2).any(axis=1).nonzero()

(array([43], dtype=int64),)

In [31]:
(boards[43] * (1 - marked[43])).sum()

646

In [29]:
marked[43]

array([[False,  True, False, False, False],
       [False,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False, False],
       [False,  True, False, False,  True]])

In [25]:
step, x

(24, 79)

In [32]:
646*79

51034